# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c72261e14d23654489ef0389c8dd995ffdfeb0d477fd998c097eadc3cdb51c711dacaa03d5885d14ae5114ff89c6445742f98e1a6cfb8e062d77452087a2cd19

test:
  secret_key_base: 059989eb288d89a240be32a52982ff15cb8c5b566e2e47c7cc22f7d604b0d64022eda9b13f69c3f17a29fe6b5fd01fe2966a63cb2ee9776e375a2e5c9b037879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
